// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHNAR.Data;

#nullable disable

namespace SHNAR.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20231129103236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InscripcionMateria", b =>
                {
                    b.Property<int>("InscripcionesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MateriasID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InscripcionesID", "MateriasID");

                    b.HasIndex("MateriasID");

                    b.ToTable("InscripcionMateria");
                });

            modelBuilder.Entity("SHNAR.Models.Alumno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InscripcionFecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("SHNAR.Models.Coordinacion", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InicioFecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Coordinacion", (string)null);
                });

            modelBuilder.Entity("SHNAR.Models.Edificio", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InicioFecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaestroNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Edificio", (string)null);
                });

            modelBuilder.Entity("SHNAR.Models.Inscripcion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlumnoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlumnoNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("MateriaNombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AlumnoID");

                    b.ToTable("Inscripcion", (string)null);
                });

            modelBuilder.Entity("SHNAR.Models.Maestro", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoordinacionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoordinacionNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Correo");

                    b.Property<int?>("EdificioID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MateriaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nombre");

                    b.HasKey("ID");

                    b.HasIndex("CoordinacionID");

                    b.HasIndex("EdificioID");

                    b.HasIndex("MateriaID");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("SHNAR.Models.Materia", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InscripcionFecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaestroNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Maestro", (string)null);
                });

            modelBuilder.Entity("InscripcionMateria", b =>
                {
                    b.HasOne("SHNAR.Models.Inscripcion", null)
                        .WithMany()
                        .HasForeignKey("InscripcionesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SHNAR.Models.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SHNAR.Models.Inscripcion", b =>
                {
                    b.HasOne("SHNAR.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoID");

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("SHNAR.Models.Maestro", b =>
                {
                    b.HasOne("SHNAR.Models.Coordinacion", "Coordinacion")
                        .WithMany("Maestros")
                        .HasForeignKey("CoordinacionID");

                    b.HasOne("SHNAR.Models.Edificio", "Edificio")
                        .WithMany("Maestros")
                        .HasForeignKey("EdificioID");

                    b.HasOne("SHNAR.Models.Materia", null)
                        .WithMany("Maestros")
                        .HasForeignKey("MateriaID");

                    b.Navigation("Coordinacion");

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("SHNAR.Models.Alumno", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SHNAR.Models.Coordinacion", b =>
                {
                    b.Navigation("Maestros");
                });

            modelBuilder.Entity("SHNAR.Models.Edificio", b =>
                {
                    b.Navigation("Maestros");
                });

            modelBuilder.Entity("SHNAR.Models.Materia", b =>
                {
                    b.Navigation("Maestros");
                });
#pragma warning restore 612, 618
        }
    }
}
